### ISSUE TITLE
Confusion regarding evaluation metric.

### ISSUE THREAD

**Issue by ashwani-bhat** [declare-lab/RECCON#1]
Hi. I am not able to find any code segment which calculates F1.  F1_pos and F1_neg are clear to me. Your code calculates F1_pos and F1_neg but not F1.
![image](https://user-images.githubusercontent.com/16431244/108172128-6f982200-7122-11eb-8bde-9829651a5e89.png)

**Comment by deepanwayx** [comment]
Thanks for pointing it out. Added in https://github.com/declare-lab/RECCON/commit/8b88b68789402d54a280d1d1debeb529217d3f07
