### ISSUE TITLE
About dailydialog dataset

### ISSUE THREAD

**Issue by ZKayell** [declare-lab/RECCON#4]
Hello. I am interested in converting dailydialog from TXT format to JSON format, can you share your code? Thank you so much.

**Comment by deepanwayx** [comment]
The provided files are already in JSON format.

**Comment by deepanwayx** [comment]
The files in the `data` folder are already in JSON format.

**Comment by ZKayell** [comment]
Yes, I noticed that. However, I am still interested in the code that implements the format conversion. Any help would be greatly appreciated.

**Comment by ZKayell** [comment]
I've solved the problem. Thank you anyway.
